author = "Ryan S. Brown"
description = "Simple theme w/ SubtlePatterns background"
license = "MIT"
name = "squairy_light"
source_repo = "https://github.com/ryansb/rsb.io/tree/master/themes/squairy_light"
tags = ["", ""]
